### ISSUE TITLE
out-of-bounds Error When using custom RPC 

### ISSUE THREAD

**Issue by risasoft** [xrchz/rocketarb#21]
I tried using rocketarb when my primary client is not synced and used my fallback as custom RPC. Rocketarb gives me out of bounds exception when creatign the arb transaction.

Here are detailed logs:

```
$ ./scripts/rocketarb-docker.sh -n --rpc http://proteus:8545
Welcome to RocketArb: Deposit!
Have you tried almost depositing your minipool using the smartnode? y
Got smartnode version 1.10.1

Creating deposit transaction by executing smartnode: docker exec rocketpool_node /go/bin/rocketpool api node deposit 8000000000000000000 0.14 6131696543806149 true false
2023/08/15 16:46:02 Primary execution client is still syncing (100.00%), using fallback execution client...
2023/08/15 16:46:02 Primary execution client is still syncing (100.00%), using fallback execution client...
Got deposit transaction data from smartnode
Creating arb transaction
/app/node_modules/@ethersproject/logger/lib/index.js:238
        var error = new Error(message);
                    ^

Error: value out-of-bounds (argument="ethAmount", value={"type":"BigNumber","hex":"-0xa6fdd7f434f4b2fd"}, code=INVALID_ARGUMENT, version=abi/5.7.0)
    at Logger.makeError (/app/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/app/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at Logger.throwArgumentError (/app/node_modules/@ethersproject/logger/lib/index.js:250:21)
    at Coder._throwError (/app/node_modules/@ethersproject/abi/lib/coders/abstract-coder.js:41:16)
    at NumberCoder.encode (/app/node_modules/@ethersproject/abi/lib/coders/number.js:46:18)
    at /app/node_modules/@ethersproject/abi/lib/coders/array.js:74:19
    at Array.forEach (<anonymous>)
    at pack (/app/node_modules/@ethersproject/abi/lib/coders/array.js:60:12)
    at TupleCoder.encode (/app/node_modules/@ethersproject/abi/lib/coders/tuple.js:71:33)
    at AbiCoder.encode (/app/node_modules/@ethersproject/abi/lib/abi-coder.js:91:15) {
  reason: 'value out-of-bounds',
  code: 'INVALID_ARGUMENT',
  argument: 'ethAmount',
  value: BigNumber { _hex: '-0xa6fdd7f434f4b2fd', _isBigNumber: true }
}

Node.js v19.5.0


```

**Comment by xrchz** [comment]
The problem is that the deposit pool is overfull. It needs to be at most full for depositing a minipool to enable minting new rETH.
