### ISSUE TITLE
Doesn't work with smartnode 1.11.12

### ISSUE THREAD

**Issue by igg2** [xrchz/rocketarb#23]
Here's the output from a dry run:
```
$ ./scripts/rocketarb-docker.sh --dry-run
Welcome to RocketArb: Deposit!
Have you tried almost depositing your minipool using the smartnode? y
Got smartnode version 1.11.2

Creating deposit transaction by executing smartnode: docker exec rocketpool_node /go/bin/rocketpool api node deposit 8000000000000000000 0.14 533611257236573 true false
Got deposit transaction data from smartnode
Creating arb transaction
/app/node_modules/@ethersproject/logger/lib/index.js:238
        var error = new Error(message);
                    ^

Error: value out-of-bounds (argument="ethAmount", value={"type":"BigNumber","hex":"-0x55469ba6564b81869a"}, code=INVALID_ARGUMENT, version=abi/5.7.0)
    at Logger.makeError (/app/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/app/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at Logger.throwArgumentError (/app/node_modules/@ethersproject/logger/lib/index.js:250:21)
    at Coder._throwError (/app/node_modules/@ethersproject/abi/lib/coders/abstract-coder.js:41:16)
    at NumberCoder.encode (/app/node_modules/@ethersproject/abi/lib/coders/number.js:46:18)
    at /app/node_modules/@ethersproject/abi/lib/coders/array.js:74:19
    at Array.forEach (<anonymous>)
    at pack (/app/node_modules/@ethersproject/abi/lib/coders/array.js:60:12)
    at TupleCoder.encode (/app/node_modules/@ethersproject/abi/lib/coders/tuple.js:71:33)
    at AbiCoder.encode (/app/node_modules/@ethersproject/abi/lib/abi-coder.js:91:15) {
  reason: 'value out-of-bounds',
  code: 'INVALID_ARGUMENT',
  argument: 'ethAmount',
  value: BigNumber { _hex: '-0x55469ba6564b81869a', _isBigNumber: true }
}

Node.js v19.9.0
```

**Comment by xrchz** [comment]
The issue is that the deposit pool is overfull. You need the deposit pool balance to be at or under 18k ETH.
